version: "3.4"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
  REACT_APP_API_HOST: "www.covershot.app"
  HOST: "frontend"
services:
  go:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    image: "100418366104.dkr.ecr.us-east-2.amazonaws.com/fundfi:fundfi-go"
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
 
  frontend:
    environment:
      <<: *QUICKSTART_ENVIRONMENT
    networks:
      - "quickstart"
    image: "frontend"
    # image: "100418366104.dkr.ecr.us-east-2.amazonaws.com/fundfi:frontend"
    # build:
    #     dockerfile: ./frontend/Dockerfile
    #     context: .
    ports: ["3000:3000"]
  nginx:
    networks:
      - "quickstart"
    build:
        dockerfile: ./nginx/Dockerfile
        context: .
    ports:
        - 80:80
        - 443:443
    depends_on:
        - frontend
networks:
  quickstart:
    name: quickstart
